import type { INodeProperties } from 'n8n-workflow';

export const mediaOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['media'] } },
		options: [
			{ name: 'Delete', value: 'delete', action: 'Delete a media file', description: '**An AI agent must never call this.** Administrative: it destroys the user\'s data irreversibly. Permanently deletes one downloaded media file from local storage — the bytes are gone and SocialMate cannot get them back (the metadata row survives with state "deleted", and WhatsApp will not re-serve an expired file, so Force Download may never recover it either). Returns {success}. Nothing about reading, describing or replying to a message needs this. Disk housekeeping belongs in the SocialMate app (Settings → Media), which applies the retention rules the user actually chose. Requires Pro and an admin-scope key.' },
			{ name: 'Download File', value: 'getFile', action: 'Download a media file', description: 'Downloads one media item\'s decrypted bytes and returns them as binary data (default output field "data"), with the item\'s metadata as the JSON. Needs the media ID from Get Many or a media.discovered trigger event. Use it to fetch an image, document or voice note for a model to read, transcribe or forward. It only works once the file is mirrored locally: an item whose state is not "downloaded" fails with a 409 — call Force Download, wait for the state to become "downloaded", then retry. When a preview is enough, prefer Download Thumbnail: it is a fraction of the size. Available on every tier.' },
			{ name: 'Download Thumbnail', value: 'getThumbnail', action: 'Download a thumbnail', description: 'Downloads a media item\'s small JPEG thumbnail as binary data (default output field "data"); the JSON carries only the item\'s ID and a thumbnail flag. Far lighter than Download File — use it whenever a preview is enough, e.g. letting a vision model glance at an image without pulling a full video or document. Only images and videos carry one: an item with neither a stored nor an inline thumbnail returns 404, and the thumbnail is never the item\'s real file, so never treat it as the document itself. For the actual bytes use Download File. Available on every tier.' },
			{ name: 'Force Download', value: 'forceDownload', action: 'Force a download', description: 'Asks the server to mirror a media item\'s bytes to local disk, and returns immediately with {success: true, state} — the download runs in the background, so state is typically "queued", NOT "downloaded". It returns no bytes at all. Use it when Get or Download File reports an item is not downloaded yet: call this, poll Get until state is "downloaded", then call Download File for the bytes. Media that arrives normally is downloaded automatically, so this is only for what was skipped, expired or failed — and WhatsApp cannot always re-serve an old file, in which case the state settles on "failed". Requires Pro.' },
			{ name: 'Get', value: 'get', action: 'Get media metadata', description: 'Returns one media item\'s metadata by its ID — {messageId, chatId, type, mimeType, fileName, fileSize, caption, direction, width, height, durationSec, isVoice, state, downloadedAt, aiContext, needsContext, apiPath, thumbnailApiPath} — and never the bytes. The field to branch on is state: only "downloaded" means the file is mirrored locally (and only then is apiPath non-null). Use it to check whether a file is ready before fetching it, or to read the description an agent cached earlier with Set Context (needsContext true = nobody has described it yet). For the bytes use Download File, for a cheap preview Download Thumbnail, and to make an undownloaded item available Force Download. Available on every tier.' },
			{ name: 'Get Download Queue', value: 'getDownloadQueue', action: 'Get the download queue', description: 'Administrative — returns the media downloader\'s live, SERVER-WIDE state: {active, pending, failed, attemptsToday, dailyCap, paused, currentlyDownloading}, where currentlyDownloading lists what is in flight right now. Use it in a monitoring workflow to see whether downloads are flowing, held (paused true) or capped out (attemptsToday at dailyCap — the reason new media stops arriving). It spans every account and ignores the selected one, and it is not a media list: for individual items and their state use Get Many, for one item Get, and for an account\'s own storage totals Get Stats. Available on every tier.' },
			{ name: 'Get Many', value: 'getMany', action: 'Get many media items', description: 'Lists this account\'s media items, newest first, with optional filters (chat, type, direction, state, search, and Has Cached Context). Returns {data, pagination} where each item carries its ID, type, fileName, fileSize, caption, state, needsContext and apiPath — pass that ID to Download File, Get or Set Context. Use it to find the files shared in a chat, or (with Has Cached Context = No) to sweep up exactly the media an agent still has to analyze. It returns metadata only, never bytes, and an item is fetchable only once its state is "downloaded". Available on every tier.' },
			{ name: 'Get Stats', value: 'getStats', action: 'Get media stats', description: 'Returns this account\'s media storage totals: {total, downloaded, pending, queued, downloading, failed, skipped, expired, totalBytes, pendingBytes, byType, oldestDownloadedAt, newestDownloadedAt}, where byType breaks the count and bytes down per media kind. Use it to report how much disk the archive is using, or to spot a backlog (failed or pending climbing). It is counts and bytes only — it names no files and returns no IDs, so to find actual items use Get Many; for the download worker\'s live, server-wide state across every account, use Get Download Queue. Available on every tier.' },
			{ name: 'Run Cleanup', value: 'cleanup', action: 'Run media cleanup', description: '**An AI agent must never call this.** Administrative: it destroys the user\'s data irreversibly, across every account on the server. Applies the retention and storage-quota rules immediately — deleting media older than the retention window and LRU-evicting more until the archive is under quota — and returns {timeEvictions, quotaEvictions, bytesFreed}. Those bytes are unrecoverable, and the sweep is NOT limited to the selected account. It already runs automatically on a schedule using the settings the user chose, so no workflow ever needs to force it; forcing it can delete files another workflow was about to read. Do it in the SocialMate app (Settings → Media). Requires Pro and an admin-scope key.' },
			{ name: 'Set Context', value: 'setContext', action: 'Set media context', description: 'Caches the description or transcript YOUR AI produced for a media item (Agent Memory), so the same photo/voice note/document is never re-analyzed. It then comes back already described inside Get AI Context. SocialMate stores your description; it never generates one. Requires Pro.' },
		],
		default: 'getMany',
	},
];

const mediaIdProperty: INodeProperties = {
	displayName: 'Media ID',
	name: 'mediaId',
	type: 'string',
	default: '',
	required: true,
	description: 'The media item\'s ID, as returned by Get Many or a media.discovered trigger event',
	displayOptions: { show: { resource: ['media'], operation: ['get', 'getFile', 'getThumbnail', 'forceDownload', 'delete', 'setContext'] } },
};

export const mediaFields: INodeProperties[] = [
	mediaIdProperty,
	{
		displayName: 'Put Output File in Field',
		name: 'binaryPropertyName',
		type: 'string',
		default: 'data',
		required: true,
		hint: 'The name of the output binary field to put the downloaded file in',
		displayOptions: { show: { resource: ['media'], operation: ['getFile', 'getThumbnail'] } },
	},
	{
		displayName: 'Context',
		name: 'context',
		type: 'string',
		typeOptions: { rows: 3 },
		default: '',
		required: true,
		description: 'The description or transcript your model produced for this media. Cached so it is never re-analyzed.',
		displayOptions: { show: { resource: ['media'], operation: ['setContext'] } },
	},
	{
		displayName: 'Options',
		name: 'contextOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: { resource: ['media'], operation: ['setContext'] } },
		options: [
			{ displayName: 'Source', name: 'source', type: 'string', default: '', description: 'What produced the context, e.g. "gpt-4o" or "whisper-1"' },
			{ displayName: 'Overwrite', name: 'overwrite', type: 'boolean', default: true, description: 'Whether to replace existing context. Turn off to fail (409) if the item already has context.' },
		],
	},
	{
		displayName: 'Filters',
		name: 'mediaFilters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: { show: { resource: ['media'], operation: ['getMany'] } },
		options: [
			{ displayName: 'Chat ID', name: 'chatId', type: 'string', default: '', description: 'Restrict to one chat — a phone number in international format (with country code) or a group JID ending in @g.us' },
			{
				displayName: 'Direction',
				name: 'direction',
				type: 'options',
				default: 'all',
				options: ['all', 'received', 'sent'].map((v) => ({ name: v, value: v })),
			},
			{
				displayName: 'Has Cached Context',
				name: 'hasContext',
				type: 'options',
				default: 'all',
				description: 'Agent Memory: filter by whether the item already has a saved AI description. Pick "no" to list only what your agent still needs to analyze.',
				options: [
					{ name: 'All', value: 'all' },
					{ name: 'Yes (Already Described)', value: 'true' },
					{ name: 'No (Needs Analysis)', value: 'false' },
				],
			},
			{ displayName: 'Search', name: 'search', type: 'string', default: '' },
			{
				displayName: 'Sort',
				name: 'sort',
				type: 'options',
				default: 'newest',
				options: ['newest', 'oldest', 'biggest', 'smallest'].map((v) => ({ name: v, value: v })),
			},
			{
				displayName: 'State',
				name: 'state',
				type: 'options',
				default: 'all',
				options: ['all', 'pending', 'queued', 'downloading', 'downloaded', 'failed', 'skipped', 'expired', 'deleted'].map((v) => ({ name: v, value: v })),
			},
			{
				displayName: 'Type',
				name: 'type',
				type: 'options',
				default: 'all',
				options: ['all', 'image', 'video', 'audio', 'voice', 'document', 'sticker'].map((v) => ({ name: v, value: v })),
			},
		],
	},
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		description: 'Whether to return all results or only up to a given limit',
		displayOptions: { show: { resource: ['media'], operation: ['getMany'] } },
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		typeOptions: { minValue: 1 },
		default: 50,
		description: 'Max number of results to return',
		displayOptions: { show: { resource: ['media'], operation: ['getMany'], returnAll: [false] } },
	},
];
